/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List live and upcoming holds the caller may release
         * @description Holds that have not ended yet, filtered to the ones this caller could act on: their own, their teams', or everything for an admin.
         */
        get: operations["list"];
        put?: never;
        /**
         * Hold seats for a team over a date range
         * @description Never force-cancels a booking. Returns a partial-success report naming which seats were held and which were left alone because somebody already holds them, and on which day.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim a seat for a date
         * @description Replaying the same Idempotency-Key returns the original booking instead of a 409.
         */
        post: operations["claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check in to today's booking
         * @description Only the owner may check in, and only for today's booking.
         */
        post: operations["checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move to a different seat on a date
         * @description Atomically cancels whatever the caller holds that day and claims the new seat. A target seat that cannot be claimed leaves the original booking untouched and ACTIVE.
         */
        post: operations["move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the floor/zone/table/seat layout with each seat's state for a date
         * @description Defaults to today (office clock) when date is omitted. One HTTP round trip: every seat's booking and team-hold state for the date is resolved in a bounded number of queries, never one per seat, so the response scales with the floor plan, not with how many seats happen to be booked.
         */
        get: operations["seatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seatmap/horizon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How full each bookable day is, for the date strip
         * @description Today through the configured booking horizon, one entry per day: how many desks are in service, how many are claimed, and which desk you already hold that day. Answered in three queries for the whole range rather than one seat map per day.
         */
        get: operations["horizon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Teams the caller may hold seats for
         * @description Every team for an admin; only the teams they manage for a manager — the same rule the create endpoint enforces.
         */
        get: operations["teams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own bookings in a date range
         * @description Defaults to today through the end of the booking window when from/to are omitted.
         */
        get: operations["mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Release a hold early
         * @description The hold's creator, the manager of the team it is for, or an admin may release it.
         */
        delete: operations["release"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel a booking
         * @description The owner, the manager of a team the owner belongs to, or an admin may cancel.
         */
        delete: operations["cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateReservationRequest: {
            /**
             * Format: int64
             * @example 3
             */
            teamId: number;
            /** @description Seats to hold for the team. */
            seatIds: number[];
            /**
             * Format: date
             * @example 2026-08-10
             */
            startDate: string;
            /**
             * Format: date
             * @example 2026-08-12
             */
            endDate: string;
            /**
             * @description Defaults to the configured team-block release time when omitted.
             * @example 10:00
             */
            releaseAtTime?: string;
        };
        HeldSeat: {
            /** Format: int64 */
            reservationId?: number;
            /** Format: int64 */
            seatId?: number;
            seatLabel?: string;
        };
        ReservationReport: {
            /** Format: int64 */
            teamId?: number;
            teamName?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            held?: components["schemas"]["HeldSeat"][];
            unavailable?: components["schemas"]["UnavailableSeat"][];
        };
        UnavailableSeat: {
            /** Format: int64 */
            seatId?: number;
            seatLabel?: string;
            /** Format: date */
            conflictingDate?: string;
            /** Format: int64 */
            conflictingUserId?: number;
            conflictingUserDisplayName?: string;
        };
        ClaimBookingRequest: {
            /**
             * Format: int64
             * @description The seat to claim.
             * @example 42
             */
            seatId: number;
            /**
             * Format: date
             * @description ISO date within the booking window.
             * @example 2026-08-10
             */
            date: string;
        };
        BookingResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            seatId?: number;
            seatLabel?: string;
            /** Format: int64 */
            userId?: number;
            userDisplayName?: string;
            /** Format: date */
            bookingDate?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "CANCELLED" | "RELEASED_NO_SHOW";
            /** Format: date-time */
            checkedInAt?: string;
            idempotencyKey?: string;
        };
        MoveBookingRequest: {
            /**
             * Format: int64
             * @description The seat to move to.
             * @example 43
             */
            seatId: number;
            /**
             * Format: date
             * @description ISO date within the booking window.
             * @example 2026-08-10
             */
            date: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        CurrentUserResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            displayName?: string;
            /** @enum {string} */
            role?: "EMPLOYEE" | "MANAGER" | "ADMIN";
            /** @enum {string} */
            provider?: "LOCAL" | "ENTRA";
        };
        LoginResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
            user?: components["schemas"]["CurrentUserResponse"];
        };
        FloorMapView: {
            /** Format: int64 */
            floorId?: number;
            name?: string;
            zones?: components["schemas"]["ZoneMapView"][];
        };
        SeatMapResponse: {
            /** Format: date */
            date?: string;
            floors?: components["schemas"]["FloorMapView"][];
        };
        SeatMapSeat: {
            /** Format: int64 */
            seatId?: number;
            /** @example R3-A2 */
            seatLabel?: string;
            /** @enum {string} */
            side?: "A" | "B";
            /** Format: int32 */
            seatIndex?: number;
            accessible?: boolean;
            /** @enum {string} */
            state?: "AVAILABLE" | "OCCUPIED" | "TEAM_RESERVED" | "DISABLED";
            /** Format: int64 */
            bookingId?: number;
            /** Format: int64 */
            occupantUserId?: number;
            occupantDisplayName?: string;
            checkedIn?: boolean;
            /** Format: int64 */
            reservedForTeamId?: number;
            reservedForTeamName?: string;
            reservedUntil?: string;
        };
        TableMapView: {
            /** Format: int64 */
            tableId?: number;
            label?: string;
            /** Format: int32 */
            capacity?: number;
            /** Format: int32 */
            posX?: number;
            /** Format: int32 */
            posY?: number;
            /** Format: int32 */
            rotation?: number;
            seats?: components["schemas"]["SeatMapSeat"][];
        };
        ZoneMapView: {
            /** Format: int64 */
            zoneId?: number;
            name?: string;
            tables?: components["schemas"]["TableMapView"][];
        };
        DayAvailabilityView: {
            /** Format: date */
            date?: string;
            /**
             * Format: int32
             * @example 102
             */
            bookableSeats?: number;
            /**
             * Format: int32
             * @example 43
             */
            bookedSeats?: number;
            /** @example R5-A1 */
            yourSeatLabel?: string | null;
            /** @example true */
            bookable?: boolean;
        };
        ReservationView: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            seatId?: number;
            seatLabel?: string;
            /** Format: int64 */
            teamId?: number;
            teamName?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            releaseAtTime?: string;
            createdByName?: string;
            enforcedNow?: boolean;
        };
        TeamView: {
            /**
             * Format: int64
             * @example 3
             */
            id?: number;
            /** @example Platform */
            name?: string;
            /** @description Display name of the team's manager, when one is set. */
            managerName?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's holds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservationRequest"];
            };
        };
        responses: {
            /** @description The partial-success report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationReport"];
                };
            };
            /** @description The caller is neither a manager nor an admin, or does not manage that team. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationReport"];
                };
            };
            /** @description The team, or one of the seat ids, does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationReport"];
                };
            };
        };
    };
    claim: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key; a repeat returns the original booking. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimBookingRequest"];
            };
        };
        responses: {
            /** @description The seat is now held by the caller. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookingResponse"];
                };
            };
            /** @description The date is outside the booking window. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookingResponse"];
                };
            };
            /** @description The seat is held for a team the caller is not in. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookingResponse"];
                };
            };
            /** @description Already booked (by someone else, or by the caller elsewhere). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookingResponse"];
                };
            };
        };
    };
    checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checked in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookingResponse"];
                };
            };
        };
    };
    move: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveBookingRequest"];
            };
        };
        responses: {
            /** @description Now holding the new seat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookingResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    seatmap: {
        parameters: {
            query?: {
                /** @description ISO date (yyyy-MM-dd). Defaults to today in the office timezone. */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The floor map for the requested date. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeatMapResponse"];
                };
            };
        };
    };
    horizon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per bookable day, today first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DayAvailabilityView"][];
                };
            };
        };
    };
    teams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's teams. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamView"][];
                };
            };
        };
    };
    mine: {
        parameters: {
            query?: {
                /** @description Defaults to today in the office timezone. */
                from?: string;
                /** @description Defaults to the end of the booking window. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's bookings in the range, earliest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookingResponse"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    release: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Released. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The caller may not release this hold. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No reservation with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The booking is now CANCELLED. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookingResponse"];
                };
            };
            /** @description The caller does not own this booking. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookingResponse"];
                };
            };
            /** @description No booking with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookingResponse"];
                };
            };
        };
    };
}
