-- DeskDibs core schema.
--
-- The two partial unique indexes at the bottom of this file ARE the anti-double-booking
-- design. They are enforced below the application, so no application bug, lost race,
-- retry storm, or future refactor can violate them. Never replace them with an
-- application-level lock or a SELECT ... FOR UPDATE pre-check.

-- ─── People ──────────────────────────────────────────────────────────────────

CREATE TABLE app_user (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Microsoft Entra ID `oid`. Null until the user has signed in via SSO.
    external_id  varchar(100),
    email        varchar(320)  NOT NULL,
    display_name varchar(200)  NOT NULL,
    avatar_url   varchar(500),
    role         varchar(20)   NOT NULL DEFAULT 'EMPLOYEE',
    active       boolean       NOT NULL DEFAULT true,
    created_at   timestamptz   NOT NULL DEFAULT now(),
    updated_at   timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT uq_app_user_external_id UNIQUE (external_id),
    CONSTRAINT uq_app_user_email       UNIQUE (email),
    CONSTRAINT ck_app_user_role        CHECK (role IN ('EMPLOYEE', 'MANAGER', 'ADMIN'))
);

CREATE TABLE team (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(120) NOT NULL,
    manager_user_id bigint,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uq_team_name    UNIQUE (name),
    CONSTRAINT fk_team_manager FOREIGN KEY (manager_user_id) REFERENCES app_user (id) ON DELETE SET NULL
);

CREATE INDEX ix_team_manager ON team (manager_user_id);

-- Many-to-many on purpose: a person may sit with more than one group.
CREATE TABLE team_member (
    team_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT pk_team_member      PRIMARY KEY (team_id, user_id),
    CONSTRAINT fk_team_member_team FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE,
    CONSTRAINT fk_team_member_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

-- The primary key already indexes (team_id, ...); this covers the reverse lookup.
CREATE INDEX ix_team_member_user ON team_member (user_id);

-- ─── Layout (data, not code) ─────────────────────────────────────────────────

CREATE TABLE floor (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(120) NOT NULL,
    display_order int          NOT NULL DEFAULT 0,
    CONSTRAINT uq_floor_name UNIQUE (name)
);

CREATE TABLE zone (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_id      bigint       NOT NULL,
    name          varchar(120) NOT NULL,
    display_order int          NOT NULL DEFAULT 0,
    CONSTRAINT uq_zone_floor_name UNIQUE (floor_id, name),
    CONSTRAINT fk_zone_floor      FOREIGN KEY (floor_id) REFERENCES floor (id) ON DELETE CASCADE
);

-- `table` is reserved in SQL, hence desk_table.
-- pos_x/pos_y/rotation are logical layout coordinates; the frontend renders from them,
-- so moving a table moves its seats for free.
CREATE TABLE desk_table (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id  bigint      NOT NULL,
    label    varchar(40) NOT NULL,
    capacity int         NOT NULL,
    pos_x    int         NOT NULL,
    pos_y    int         NOT NULL,
    rotation int         NOT NULL DEFAULT 0,
    CONSTRAINT uq_desk_table_label   UNIQUE (label),
    CONSTRAINT fk_desk_table_zone    FOREIGN KEY (zone_id) REFERENCES zone (id) ON DELETE CASCADE,
    -- Seats sit in equal numbers on side A and side B, so capacity must be even.
    CONSTRAINT ck_desk_table_capacity CHECK (capacity > 0 AND capacity % 2 = 0)
);

CREATE INDEX ix_desk_table_zone ON desk_table (zone_id);

CREATE TABLE seat (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id   bigint      NOT NULL,
    label      varchar(40) NOT NULL,
    side       varchar(1)  NOT NULL,
    seat_index int         NOT NULL,
    accessible boolean     NOT NULL DEFAULT false,
    status     varchar(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uq_seat_label            UNIQUE (label),
    CONSTRAINT uq_seat_table_side_index UNIQUE (table_id, side, seat_index),
    CONSTRAINT fk_seat_table            FOREIGN KEY (table_id) REFERENCES desk_table (id) ON DELETE CASCADE,
    CONSTRAINT ck_seat_side             CHECK (side IN ('A', 'B')),
    CONSTRAINT ck_seat_index            CHECK (seat_index > 0),
    CONSTRAINT ck_seat_status           CHECK (status IN ('ACTIVE', 'DISABLED', 'BROKEN'))
);

CREATE INDEX ix_seat_table ON seat (table_id);

-- ─── Bookings ────────────────────────────────────────────────────────────────

CREATE TABLE booking (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_id         bigint      NOT NULL,
    user_id         bigint      NOT NULL,
    booking_date    date        NOT NULL,
    status          varchar(24) NOT NULL DEFAULT 'ACTIVE',
    checked_in_at   timestamptz,
    idempotency_key text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    -- RESTRICT, not CASCADE: a seat leaving the floor plan must not silently delete
    -- somebody's booking history. Seats are soft-disabled instead.
    CONSTRAINT fk_booking_seat FOREIGN KEY (seat_id) REFERENCES seat (id) ON DELETE RESTRICT,
    CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_booking_status CHECK (status IN ('ACTIVE', 'CANCELLED', 'RELEASED_NO_SHOW'))
);

-- ═════════════════════════════════════════════════════════════════════════════
-- THE INVARIANT. A seat has at most one ACTIVE booking per date; a person holds
-- at most one ACTIVE booking per date. Partial (WHERE status = 'ACTIVE') so that
-- cancelled and auto-released rows drop out of the index and free the slot again.
-- ═════════════════════════════════════════════════════════════════════════════
CREATE UNIQUE INDEX uq_seat_active_per_date
    ON booking (seat_id, booking_date) WHERE status = 'ACTIVE';

CREATE UNIQUE INDEX uq_user_active_per_date
    ON booking (user_id, booking_date) WHERE status = 'ACTIVE';

-- A double-click, a retry, or a flaky-network resend returns the original result
-- instead of a confusing 409 against yourself.
CREATE UNIQUE INDEX uq_booking_idempotency
    ON booking (idempotency_key) WHERE idempotency_key IS NOT NULL;

-- Supporting indexes for the read paths: the day snapshot, and "my bookings".
CREATE INDEX ix_booking_date_status ON booking (booking_date, status);
CREATE INDEX ix_booking_user_date   ON booking (user_id, booking_date);

-- Soft team holds. Past release_at_time the claim check simply stops enforcing
-- them — no job, no state change, nothing to go wrong.
CREATE TABLE seat_reservation (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_id         bigint      NOT NULL,
    team_id         bigint      NOT NULL,
    start_date      date        NOT NULL,
    end_date        date        NOT NULL,
    release_at_time time        NOT NULL DEFAULT '10:00',
    created_by      bigint      NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_seat_reservation_seat    FOREIGN KEY (seat_id)    REFERENCES seat (id)     ON DELETE CASCADE,
    CONSTRAINT fk_seat_reservation_team    FOREIGN KEY (team_id)    REFERENCES team (id)     ON DELETE CASCADE,
    CONSTRAINT fk_seat_reservation_creator FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_seat_reservation_dates   CHECK (end_date >= start_date)
);

CREATE INDEX ix_seat_reservation_seat_dates ON seat_reservation (seat_id, start_date, end_date);
CREATE INDEX ix_seat_reservation_team       ON seat_reservation (team_id);
CREATE INDEX ix_seat_reservation_creator    ON seat_reservation (created_by);
